### ISSUE TITLE
Compiling on Fedora 33 using Python 3 fails

### ISSUE THREAD

**Issue by Finnboy94** [soundmud/soundrts#129]
With soundrts 1.3.5, trying
python setup.py build
on Fedora 33 gave this error:
[user@palvelin soundrts]$ python setup.py build                                
Traceback (most recent call last):                                              
  File "setup.py", line 31, in <module>                                         
    TMP = os.environ["TMP"]                                                     
  File "/usr/lib64/python3.8/os.py", line 675, in __getitem__                   
    raise KeyError(key) from None                                               
KeyError: 'TMP'

**Comment by Finnboy94** [comment]
That's to say, Fedora 32.

**Comment by soundmud** [comment]
At the moment, setup.py is only supposed to build the Windows executable.
It should be possible to launch the game with a "python soundrts.py" command.
