### ISSUE TITLE
my map is tracebacking whole game lol.

### ISSUE THREAD

**Issue by paxcoder** [soundmud/soundrts#140]
2021-12-22 18:25:29,506 ERROR: error
Traceback (most recent call last):
  File "v1.3.5:soundrts\clientmain.py", line 337, in main
  File "v1.3.5:soundrts\clientmain.py", line 315, in main_menu
  File "v1.3.5:soundrts\clientmenu.py", line 304, in loop
  File "v1.3.5:soundrts\clientmenu.py", line 299, in run
  File "v1.3.5:soundrts\clientmenu.py", line 261, in _execute_choice
  File "v1.3.5:soundrts\clientmain.py", line 227, in single_player_menu
  File "v1.3.5:soundrts\clientmenu.py", line 304, in loop
  File "v1.3.5:soundrts\clientmenu.py", line 299, in run
  File "v1.3.5:soundrts\clientmenu.py", line 261, in _execute_choice
  File "v1.3.5:soundrts\clientmain.py", line 217, in run
  File "v1.3.5:soundrts\clientmenu.py", line 299, in run
  File "v1.3.5:soundrts\clientmenu.py", line 261, in _execute_choice
  File "v1.3.5:soundrts\clientmain.py", line 210, in _open_players_menu
  File "v1.3.5:soundrts\clientmenu.py", line 304, in loop
  File "v1.3.5:soundrts\clientmenu.py", line 299, in run
  File "v1.3.5:soundrts\clientmenu.py", line 261, in _execute_choice
  File "v1.3.5:soundrts\clientmain.py", line 171, in _run_game
  File "v1.3.5:soundrts\game.py", line 105, in run
  File "v1.3.5:soundrts\world.py", line 971, in populate_map
  File "v1.3.5:soundrts\worldplayerbase.py", line 684, in init_position
KeyError: 'a3'
map content
nb_players_min 2
nb_players_max 3
global_food_limit 100000000000000
square_width 12
nb_lines 1
nb_columns 10
west_east path a1 i1
goldmine 1000 a1 b1 c1 d1 e1 f1 g1 h1 
woods 100 a1 b1 c1 d1 e1 f1 g1 h1 
nb_meadows_by_square 6
starting_resources 100 100
starting_units 1 dragon_tower 1 slave 1 sheep_farm
starting_squares a1 a3 a6

**Comment by soundmud** [comment]
KeyError: 'a3' means that there is no a3 square
Name your starting_squares a1 c1 f1 or something like that.
